data:
    name: homographiesTartan
    data_dir: syntheticForestData/imageData/
    train_size: 40000
    val_size: 5000
    batch_size: 32
    num_workers: 4 
    homography:
        difficulty: 0.5
        max_angle: 5
    photometric:
        name: lg
model:
    name: two_view_pipeline
    extractor:
        name: gluefactory_nonfree.superpoint
        max_num_keypoints: 512
        force_num_keypoints: True
        detection_threshold: 0.0
        nms_radius: 3
        trainable: False
    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3
    matcher:
        name: matchers.lightglue
        filter_threshold: 0.1
        flash: true # false
        checkpointed: true
        useEpipolar : false
        scrambleWeights: true
train:
    seed: 42
    epochs: 60
    log_every_iter: 250 # 100
    eval_every_iter: 500
    lr: 1e-4 
    lr_schedule:
        start: 45 
        type: exp
        on_epoch: true
        exp_div_10: 45 # approx 0.8 decay
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
